apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  path: ./apps/podinfo
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
